#!/bin/bash


#apt

echo "Cardinal - Para instalar o SystemCall.py, preciso da sua permissão..."
echo
echo "Os pacotes que estarão instalados são: python3, python3-pip, SpeechRecognition, pyqt5 e pygame"
echo "Isso pode ser verificado no arquivo lendo-o com $ cat install"

#sudo -s
#apt-get install python3 -y
#apt-get install python3-pip -y

#pip3


#pip3 install SpeechRecognition
#pip3 install pyqt5
#pip3 install pygame

#cp and mkdir

#exit
echo "Criando pasta SystemCallApp"


mkdir $HOME/SystemCallApp

echo "Copiando arquivos principais..."

cp main.py $HOME/SystemCallApp
cp stacia.py $HOME/SystemCallApp
cp init $HOME/SystemCallApp
cp "staciawindow.ui" $HOME/SystemCallApp
cp startscapp.sh $HOME
cp assets/ -r $HOME/SystemCallApp/


echo "Criando atalho no desktop..."

#movendo systemcall-py.desktop
python3 mkdesktop.py
cp systemcall-py.desktop $HOME/Desktop



#Login SAO

echo "Copiando arquivos adicionais..."


cp secret/ -r $HOME/SystemCallApp/
